# -*- coding: utf-8 -*-
"""Updated_Obesity .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFcz0gUz6LZJ2ctfA7Femlx2TNn2RSXY

Importing Required Packeges
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.metrics import roc_auc_score, roc_curve
from sklearn.preprocessing import label_binarize

from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/CSE422 Project/Obesity_Level_Dataset.csv')
df.head()

df.isnull().sum()

df.info()

"""Check For Imbalanced Dataset"""

print("Unique Classes:")
print(df["NObeyesdad"].unique())
class_counts = df["NObeyesdad"].value_counts()
print("\nClass Distribution:")
print(class_counts)

if class_counts.nunique() == 1:
    print("\nThe dataset is perfectly balanced.")
else:
    print("\nThe dataset is imbalanced.")

plt.figure()
class_counts.plot(kind='bar')
plt.xlabel("Output Classes")
plt.ylabel("Number of Instances")
plt.title("Class Distribution of Obesity Levels")
plt.show()

df_encoded = pd.get_dummies(df, drop_first=True)


corr_matrix = df_encoded.corr()

plt.figure(figsize=(16, 12))
sns.heatmap(corr_matrix, cmap='coolwarm', annot=False)
plt.title("Correlation Heatmap (After Encoding)")
plt.show()

"""EDA, Pre-processing"""

df_before = df.copy()

# ----- Missing Value Imputation -----
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['family_history_with_overweight'] = df['family_history_with_overweight'].fillna(
    df['family_history_with_overweight'].mode()[0]
)
df['CH2O'] = df['CH2O'].fillna(df['CH2O'].mean())

# ----- Encoding -----
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

binary_cols = ['Gender', 'family_history_with_overweight', 'FAVC', 'SMOKE']
for col in binary_cols:
    if col in df.columns:
        df[col] = le.fit_transform(df[col])

one_hot_cols = ['CAEC', 'CALC', 'MTRANS']
existing_cols = [col for col in one_hot_cols if col in df.columns]
df = pd.get_dummies(df, columns=existing_cols, drop_first=True)

df['NObeyesdad'] = le.fit_transform(df['NObeyesdad'])

df['SCC'] = df['SCC'].map({'yes': 1, 'no': 0})




X = df.drop('NObeyesdad', axis=1)
y = df['NObeyesdad']



X_temp, X_test, y_temp, y_test = train_test_split(
    X,  # This X comes from your df.drop('NObeyesdad', axis=1) above
    y,  # This y comes from your df['NObeyesdad'] above
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("After first split:")
print(f"  Temp set (train+val): {X_temp.shape}")
print(f"  Test set: {X_test.shape}")


X_train, X_val, y_train, y_val = train_test_split(
    X_temp,
    y_temp,
    test_size=0.125,
    random_state=42,
    stratify=y_temp
)

print("\nFinal splits:")
print(f"  Training set: {X_train.shape} ({len(X_train)/len(X)*100:.1f}% of total)")
print(f"  Validation set: {X_val.shape} ({len(X_val)/len(X)*100:.1f}% of total)")
print(f"  Test set: {X_test.shape} ({len(X_test)/len(X)*100:.1f}% of total)")



print("Unique dtypes in X_train:", X_train.dtypes.unique())

# Preview
print(type(X_train))
print(X_train.head())

"""KNN – Classification Model"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report

#
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)


print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

"""Logistic Regression – Classification Model"""

from sklearn.linear_model import LogisticRegression


log_reg = LogisticRegression(max_iter=1000, multi_class='multinomial')
log_reg.fit(X_train, y_train)
y_pred_lr = log_reg.predict(X_test)


print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print(classification_report(y_test, y_pred_lr))

"""Neural Network (Using TensorFlow/Keras)"""

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import SparseCategoricalCrossentropy


nn_model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(len(y.unique()), activation='softmax')
])


nn_model.compile(
    optimizer=Adam(learning_rate=0.001),
    loss=SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

history = nn_model.fit(
    X_train,
    y_train,
    epochs=20,
    batch_size=32,
    validation_data=(X_val, y_val)
)

test_loss, test_accuracy = nn_model.evaluate(X_test, y_test)
print("Neural Network Test Accuracy:", test_accuracy)

"""Unsupervised Learning – KMeans Clustering"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


X_cluster = df.drop('NObeyesdad', axis=1)
print("Shape of data used for clustering:", X_cluster.shape)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_cluster)

wcss = []

for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure()
plt.plot(range(1, 11), wcss)
plt.xlabel("Number of Clusters (K)")
plt.ylabel("WCSS")
plt.title("Elbow Method for Optimal K")
plt.show()


kmeans = KMeans(n_clusters=7, random_state=42)
cluster_labels = kmeans.fit_predict(X_scaled)
df['Cluster'] = cluster_labels

df[['Cluster']].head()
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)
plt.figure()
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=cluster_labels)
plt.xlabel("Principal Component 1")
plt.ylabel("Principal Component 2")
plt.title("KMeans Clustering Visualization")
plt.show()

pd.crosstab(df['Cluster'], df['NObeyesdad'])

"""Naive Bayes"""

model = GaussianNB()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
y_pred_train = model.predict(X_train)

train_accuracy = accuracy_score(y_train, y_pred_train)
print(f"Training Accuracy: {train_accuracy}")
test_accuracy = accuracy_score(y_test, y_pred)
print(f"Testing Accuracy: {test_accuracy}")

conf_matrix = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{conf_matrix}")

categories = ['Training Accuracy', 'Testing Accuracy']
accuracies = [train_accuracy, test_accuracy]

plt.figure(figsize=(6, 5))
plt.bar(categories, accuracies, color=['skyblue', 'salmon'], alpha=0.8)
plt.ylim(0, 1)
plt.title('NB Model Accuracy', fontsize=16)
plt.ylabel('Accuracy', fontsize=14)
plt.xticks(fontsize=12)
plt.yticks(fontsize=12)


plt.text(0, train_accuracy + 0.02, f'{train_accuracy:.2f}', ha='center', fontsize=12)
plt.text(1, test_accuracy + 0.02, f'{test_accuracy:.2f}', ha='center', fontsize=12)
plt.tight_layout()
plt.show()

report = classification_report(y_test, y_pred, output_dict=True)
print("Classification Report:")
print(classification_report(y_test, y_pred))

classes = list(report.keys())[:-3]
precision = [report[class_]['precision'] for class_ in classes]
recall = [report[class_]['recall'] for class_ in classes]

x = np.arange(len(classes))
width = 0.35

plt.figure(figsize=(10, 6))
plt.bar(x - width/2, precision, width, label='Precision', color='skyblue')
plt.bar(x + width/2, recall, width, label='Recall', color='salmon')
plt.title('Precision and Recall Comparison (Naive Bayes)', fontsize=16)
plt.xlabel('Classes', fontsize=14)
plt.ylabel('Scores', fontsize=14)
plt.xticks(x, classes, fontsize=12)
plt.ylim(0, 1)
plt.legend(fontsize=12)

for i in range(len(classes)):
    plt.text(i - width/2, precision[i] + 0.02, f'{precision[i]:.2f}', ha='center', fontsize=10)
    plt.text(i + width/2, recall[i] + 0.02, f'{recall[i]:.2f}', ha='center', fontsize=10)

plt.tight_layout()
plt.show()

"""Model Selection & Comparison Analysis"""

y_pred_knn = knn.predict(X_test)
y_pred_lr = log_reg.predict(X_test)
y_pred_nn = nn_model.predict(X_test)
y_pred_nn = y_pred_nn.argmax(axis=1)

"""Accuracy Comparison (Bar Chart)"""

from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

accuracy_scores = {
    "KNN": accuracy_score(y_test, y_pred_knn),
    "Logistic Regression": accuracy_score(y_test, y_pred_lr),
    "Neural Network": accuracy_score(y_test, y_pred_nn)
}

plt.figure()
plt.bar(accuracy_scores.keys(), accuracy_scores.values())
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.title("Model Accuracy Comparison")
plt.show()

"""Precision, Recall & F1-Score Comparison"""

from sklearn.metrics import classification_report

print("KNN Classification Report\n")
print(classification_report(y_test, y_pred_knn))

print("Logistic Regression Classification Report\n")
print(classification_report(y_test, y_pred_lr))

print("Neural Network Classification Report\n")
print(classification_report(y_test, y_pred_nn))

"""Confusion Matrix for Each Model"""

from sklearn.metrics import ConfusionMatrixDisplay

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_knn)
plt.title("KNN Confusion Matrix")
plt.show()

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_lr)
plt.title("Logistic Regression Confusion Matrix")
plt.show()

ConfusionMatrixDisplay.from_predictions(y_test, y_pred_nn)
plt.title("Neural Network Confusion Matrix")
plt.show()

"""ROC Curve & AUC Score (Multi-class)"""

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

# Binarize labels
classes = np.unique(y_test)
y_test_bin = label_binarize(y_test, classes=classes)

y_prob_knn = knn.predict_proba(X_test)
y_prob_lr = log_reg.predict_proba(X_test)
y_prob_nn = nn_model.predict(X_test)

models = {
    "KNN": y_prob_knn,
    "Logistic Regression": y_prob_lr,
    "Neural Network": y_prob_nn
}

plt.figure()

for model_name, probs in models.items():
    fpr, tpr, _ = roc_curve(y_test_bin.ravel(), probs.ravel())
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{model_name} (AUC = {roc_auc:.2f})")

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison")
plt.legend()
plt.show()

"""Final Comparison Table"""

import pandas as pd

comparison_df = pd.DataFrame({
    "Model": accuracy_scores.keys(),
    "Accuracy": accuracy_scores.values()
})

comparison_df